### ISSUE TITLE
Attributes matcher no longer supports full rspec matcher interface (like composability)

### ISSUE THREAD

**Issue by jasonkarns** [punditcommunity/pundit-matchers#107]
Prior to v3, the attributes matcher was defined using the Rspec DSL (`RSpec::Matchers.define`) which meant that the resulting matcher(s) was a subclass of rspec's built-in matcher hierarchy.

This meant that the matchers were chainable, composable, diffable, and recursive.

Now with v3, the pundit-matchers base matcher does not inherit from the core rspec matchers, and thus breaks the interfaces that rspec matchers support.

Most notably for this issue, chaining:

Before, the following worked:

```
it { is_expected.to permit_attributes(%w[
         actual_custom_rate
         estimated_custom_rate
       ])
         .and forbid_attributes(%w[
           estimated_inside_dimensions
           estimated_outside_dimensions
           actual_inside_dimensions
           actual_outside_dimensions
           estimated_cube
}
```

Now, it generates an error:
```
NoMethodError:
       undefined method `and' for #<Pundit::Matchers::PermitAttributesMatcher:0x00007f2c96d26a08 @expected_attributes=[:actual_custom_rate, :estimated_custom_rate], @options={}>
     
                 .and forbid_attributes(%w[
                 ^^^^
```

**Comment by jasonkarns** [comment]
I think including the Composable module may be all that's necessary? 

https://github.com/rspec/rspec-expectations/blob/main/lib/rspec/matchers/composable.rb

**Comment by tagliala** [comment]
Hi @jasonkarns, any chance to giva a try to #108?

> This meant that the matchers were chainable, composable, diffable, and recursive.

I've tried `and` and it works, I don't know what else I can try

**Comment by jasonkarns** [comment]
I've been OOO for a bit, so I can give the new releases a try, thank you!!!

**Comment by jasonkarns** [comment]
Updated and confirmed, the new release with these changes works a treat! thank you, @chrisalley @tagliala !
