### ISSUE TITLE
  uninitialized constant Pundit::RSpec::Matchers::Composable

### ISSUE THREAD

**Issue by steveclarke** [punditcommunity/pundit-matchers#110]
After updating to 3.1.1, I get the following error when running my specs:

`uninitialized constant Pundit::RSpec::Matchers::Composable`

Changing line 9 in `base_matcher.rb` to:

 `include ::RSpec::Matchers::Composable`

clears the error and forces namespace resolution to the top level.

**Comment by tagliala** [comment]
Hi @steveclarke , can you give a try to `bugfix/110-require-composable` branch ?

**Comment by steveclarke** [comment]
> Hi @steveclarke , can you give a try to `bugfix/110-require-composable` branch ?

That worked thanks!
