### ISSUE TITLE
Split matchers.rb file into multiple files

### ISSUE THREAD

**Issue by chrisalley** [punditcommunity/pundit-matchers#21]
Currently all of the matchers are saved in one big file, `lib/pundit/matchers.rb`. Ideally, we would split the matchers into smaller files, one file per matcher.

The reason this hasn't been done already is due to the problem of loading the matchers when the code is turned into a gem. So a PR that splits the matchers file will also need to be tested when it is turned into a gem.

**Comment by tagliala** [comment]
I was checking for [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers)'s approach

It would also be possible to remove `*_new_and_create_actions`/`*_new_and_create_actions` in favour of `*_actions(:new, :create)`/`*_actions(:edit, :update)`

I have an experimental branch on my fork

**Comment by chrisalley** [comment]
Strictly speaking we could replace `permit_action`, `permit_new_and_create_actions`, and `permit_edit_and_update_actions` with just `permit_actions`. However, following TMTOWTDI ("There's more than one way to do it"), we would lose some of the expressiveness that Ruby is known for.

**Comment by tagliala** [comment]
This is how classes can look like

```rb
def forbid_actions(*actions)
  ForbidActionsMatcher.new(*actions)
end

def forbid_new_and_create_actions
  ForbidActionsMatcher.new(:new, :create)
end

def forbid_edit_and_update_actions
  ForbidActionsMatcher.new(:edit, :update)
end
```

It would be needed to test the matcher once and then specific tests will just check that ForbidActionsMatcher will receive new with the proper parameters

**Comment by chrisalley** [comment]
This is a good approach, treating `forbid_new_and_create_actions` and `forbid_edit_and_update_actions` as redirects to `forbid_actions` (with arguments) in the code, while retaining the option for the spec author to use their preferred matcher.
