### ISSUE TITLE
Pundit Matchers 2.0

### ISSUE THREAD

**Issue by chrisalley** [punditcommunity/pundit-matchers#33]
In order to reduce complexity in this gem, I think it would be worthwhile moving toward a 2.0 release that breaks compatibility with the existing 1.x line. The idea would be to largely remain compatible with 1.x so that people don't have to change their test suites significantly.

Pundit Matchers 2.0 could include the following:

- Remove additional arguments being passed to `permit_action` and `forbid_action` (see #26)
- Use negated matcher (`is_expected.not_to`) to force the `forbid_*` behaviour instead (see #30)
- Split matchers.rb file into multiple files (see #21). This could potentially be introduced in 1.x since it's just a refactor, but we have to ensure that there's no conflict with incoming PRs.

If you have any further ideas, please list them here.

**Comment by athix** [comment]
@chrisalley any updates on this?

**Comment by chrisalley** [comment]
The gem has been dormant for while, but we could keep progressing with this. A good starting point would be to merge outstanding PRs and tidy up the 1.X code (see linked issues).

**Comment by chrisalley** [comment]
Pundit Matchers 2 has been released dropping support for Ruby 2, but without these other changes. As such, I'll close this issue, but we'll still target these issues in future major releases.
