### ISSUE TITLE
Better error message for when alias isn't configured

### ISSUE THREAD

**Issue by boardfish** [punditcommunity/pundit-matchers#35]
The error that's raised [here](https://github.com/chrisalley/pundit-matchers/blob/master/lib/pundit/matchers.rb#L194-L198) is vague. It'd help the usability of this library if a specific error could be raised - ideally, it'd be somewhere along these lines:

> Could not read the policy's `user`. You may want to configure an alias, which you can do as follows:
> ```ruby
> Pundit::Matchers.configure do |config|
>  config.user_alias = :account
> end
> ```

At present, it looks like this:

```
     Failure/Error: it { is_expected.to permit_action(:create) }
     
     NoMethodError:
       undefined method `user' for #<SomePolicy:0x0000557180320888>
       Did you mean?  super
     # /bundle_cache/ruby/2.7.0/gems/pundit-matchers-1.6.0/lib/pundit/matchers.rb:196:in `public_send'
     # /bundle_cache/ruby/2.7.0/gems/pundit-matchers-1.6.0/lib/pundit/matchers.rb:196:in `block (2 levels) in <module:Pundit>'
```

**Comment by tagliala** [comment]
Hi, I have a fix for this, but I think that this should be removed if we want to support multiple aliases (eg: `Post` policy has `user` while `Message` policy has `account`

**Comment by chrisalley** [comment]
It would be great to replace this with a solution that supports multiple aliases.

**Comment by tagliala** [comment]
It can be an extra hash to look into

Like default_user_alias (symbol and fallback)
default_user_aliases: { 'Message' => :account }

This will be easy with the refactor that I'm doing
