### ISSUE TITLE
Feature request: `permit_only_*` matcher

### ISSUE THREAD

**Issue by tagliala** [punditcommunity/pundit-matchers#41]
Hi,

apologies if this is a duplicate or if this is already possible, but I wasn't able to find a solution

In the effort of improving security and mitigate A01:2021-Broken Access Control issues, would it be possible to have a `permit_only` matcher?

At the moment I'm now using a custom approach that:

1. Defines all actions in the policy
2. Checks that the forbids `all_actions - permitted_actions`
3. Checks that the policy permits `permitted_actions` (if any left)

However, this approach has the limitation that a developer may forgot to add new actions to the spec file, so there is no guarantee that the new action is forbidden by default

I've improved the custom approach by creating a helper that uses `PolicyInfo`'s model to automatically get all the actions in a policy, but I think that having a built-in matcher with a better failure message could improve the developer experience

Ref:
- https://owasp.org/Top10/A01_2021-Broken_Access_Control/
- varvet/pundit#711

**Comment by chrisalley** [comment]
I agree that this would be a useful matcher. In line with the other matchers, `permit_only_actions` and `forbid_only_actions` would avoid ambiguity with other kinds of permitting (e.g. we might want to add `permit_only_attributes` and `forbid_only_attributes` at a later point in time).

Please do contribute a PR with the change.

**Comment by tagliala** [comment]
GPT generated:

> ### Mitigate Broken Access Control risk
> 
> When it comes to testing for access control vulnerabilities, it is important to ensure that only authorized users are able to access and perform certain actions within the system. The `permit_only_actions` method provides a simple and effective way to test this aspect of access control.
> 
> This method allows to specify only the actions that should be permitted for a given user, and verifies that all other actions are denied.
