### ISSUE TITLE
Interested in migrating to GitHub Actions?

### ISSUE THREAD

**Issue by tagliala** [punditcommunity/pundit-matchers#46]
Hi @chrisalley, thanks for the invitation.

Are you interested in migrating from Travis to GitHub Actions? I've seen that the latest build is from 5 months ago

I've did this several times in the past and it would require negligible effort on my side

**Comment by chrisalley** [comment]
Thanks for accepting the invite to the Pundit Community organisation. I'm looking at getting more people involved in the maintenance of this gem over time.

Migrating to GitHub Actions seems like a sensible step forward and could make a nice PR. Thanks.
