### ISSUE TITLE
Support for nested attributes in permit/forbid mass assignment

### ISSUE THREAD

**Issue by mattstenback** [punditcommunity/pundit-matchers#7]
The `permit_mass_assignment_of` and `forbid_mass_assignment_of` matchers don't seem to play nicely with nested attributes. Is there a different way to test these, or some sort of workaround? If not, I can try and put together a pull request.

```ruby
# In the policy
def permitted_attributes
  [ :name, address_attributes: [:line1, :line2, :city, :postal_code, :country] ]
end


# In the spec
it { should permit_mass_assignment_of(:address_attributes) }


# no worky :(
```

**Comment by chrisalley** [comment]
The `permit_mass_assignment_of` and `forbid_mass_assignment_of` matchers currently don't support nested attributes. They also don't support multiple attributes. Both would be useful additions.

There's the question of what the DSL should look like. In the example you posted, it assumes that the whole `address_attributes` should be permitted, but in practice there might be particular sub-attributes that you want to permit or forbid. Perhaps we could extend the matcher to support a variable length argument list, allowing the whole permitted (or forbidden) list to be passed to the matcher, like this:

```ruby
it do 
  is_expected.to(
    permit_mass_assignment_of(
      address_attributes: [
        :line1,
        :line2,
        :city,
        :postal_code
      ]
    )
  )
end
```

And let's say we wanted to forbid the user from changing their country, we could be specify this with the opposite matcher:

```ruby
it do 
  is_expected.to(
    forbid_mass_assignment_of(
      address_attributes: [:country]
    )
  )
end
```

This would allow the author of the spec to be explicit about exactly which attributes should be permitted or not permitted.

**Comment by seanfcarroll** [comment]
I wasn't aware Pundit supported nested policies ... in fact [it does](https://gorails.com/forum/pundit-how-to-apply-the-same-policy-to-nested-resources)

This would be a useful addition.

**Comment by chrisalley** [comment]
I updated my example code above to reflect the API decided on in #20. If we implement this, nested attributes should be supported by passing an array of arrays to the matcher.

**Comment by tagliala** [comment]
I think I can support this, but maybe there are edge cases I'm missing. I expect that

- Permitted attributes is an array
- It can only contain strings, symbols, or hashes
- hashes can contain a single attribute or an array of attributes
- hashes can also contain nested hashes

The idea is to convert attributes from `[:attr1, :attr2, { some_model_attributes: [:attr3] }]` to

```rb
[:attr1, :attr2, :'some_model_attributes[attr3]']
```

I have a working prototype also tested on a large codebase (where it found a legit error 😊 )

**Comment by chrisalley** [comment]
I'd prefer it if we could use the nested syntax I posted earlier:

```ruby
it do 
  category_attributes = [:name, :slug]
  is_expected.to(
    permit_mass_assignment_of([
      :name,
      category_attributes: category_attributes
    ])
  )
end
```

The reason is that we may want to expand this to include further levels of nesting in the future, e.g.

```ruby
it do 
  subcategory_attributes = [:name, :slug] 
  category_attributes = [:name, :slug, subcategory_attributes: subcategory_attributes]
  is_expected.to(
    permit_mass_assignment_of([
      :name,
      category_attributes: category_attributes
    ])
  )
end
```

As an MVP, supporting one level of nesting would be okay, but we may want to expand this in the future. Using nested syntax has two advantages: (1) it avoids us getting locked into a particular level of nesting (2) it more closes resembles the syntax used in actual policies (allowing for copy/paste).

**Comment by tagliala** [comment]
It is exactly what it does. Conversion is performed internally to dig into the hash and provide a helpful message, like "it is not possible to assign model_attributes[destroy]"
