### ISSUE TITLE
2.2.0 has a wrong version number (there is a breaking change we can't detect, the major version should be bumped)

### ISSUE THREAD

**Issue by tagliala** [punditcommunity/pundit-matchers#73]
Hi @chrisalley , there is an error here :(

https://github.com/punditcommunity/pundit-matchers/blob/9975dd2ec03bb762c54965b2859f0f7dbaa7c08b/pundit-matchers.gemspec#L5

I've bumped to 3.0 because Pundit 1.x support has been dropped and we cannot restrict to 1.x, so this will break usage for users relying on arguments

In this specific case, I would yank 2.2.0 and release 3.0.0

**Comment by chrisalley** [comment]
The latest version is 2.2.0: https://rubygems.org/gems/pundit-matchers/versions

Version 2.2.0 has this gem spec:

```
# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name        = 'pundit-matchers'
  s.version     = '2.2.0'
  s.summary     = 'RSpec matchers for Pundit policies'
  s.description = 'A set of RSpec matchers for testing Pundit authorisation ' \
                  'policies'
  s.authors     = ['Chris Alley']
  s.email       = 'chris@chrisalley.info'
  s.files       = Dir['lib/**/*']
  s.require_paths = ['lib']
  s.homepage    = 'https://github.com/punditcommunity/pundit-matchers'
  s.license     = 'MIT'
  s.add_runtime_dependency 'rspec-rails', '>= 3.0.0'
  s.add_development_dependency 'pundit', '~> 1.1', '>= 1.1.0'
  s.metadata['rubygems_mfa_required'] = 'true'
  s.required_ruby_version = '>= 3.0'
end
```

This is what's on the 2.x branch. The main branch contains the unreleased 3.0.0 code.

**Comment by tagliala** [comment]
Oh sorry, didn't notice

Thanks for the clarification, closing here
