### ISSUE TITLE
Clarification about conditional include

### ISSUE THREAD

**Issue by tagliala** [punditcommunity/pundit-matchers#74]
Hello,

I've seen that this conditional is here from the first version

https://github.com/punditcommunity/pundit-matchers/blob/9975dd2ec03bb762c54965b2859f0f7dbaa7c08b/lib/pundit/matchers.rb#L401-L405

I'm asking if there is any chance that Pundit is not defined at this point of the file because of the above definition of module Pundit in the same file

https://github.com/punditcommunity/pundit-matchers/blob/9975dd2ec03bb762c54965b2859f0f7dbaa7c08b/lib/pundit/matchers.rb#L5

**Comment by chrisalley** [comment]
It may not be needed. If we can confirm that, the conditional could be removed.
