### ISSUE TITLE
`not_to permit_mass_assignment` is confusing

### ISSUE THREAD

**Issue by tagliala** [punditcommunity/pundit-matchers#78]
Example:

https://github.com/punditcommunity/pundit-matchers/blob/fae8bb7bd918bb263bdb2594751c9ddd585a7449/spec/matchers/permit_mass_assignment_of_spec.rb#L5-L11

`it { is_expected.not_to permit_mass_assignment_of(%i[foo bar baz]) }` returns true, but `foo` and `bar` are permitted 

This will not be an issue in the refactor that I'm doing, because it will use `forbid_mass_assignment_of`

**Comment by chrisalley** [comment]
This issue is a lot like #30. We should ensure all of the matchers behave consistently when using `is_expected.not_to`.

**Comment by tagliala** [comment]
Closed via #81
