### ISSUE TITLE
Proposal: alias or rename `permit_mass_assignment_of`

### ISSUE THREAD

**Issue by jasonkarns** [punditcommunity/pundit-matchers#94]
I'm bringing this up since it seems that there is some refactoring taking place with the attribute matcher(s).

Context: we're using Pundit with Graphiti (Graphiti is an api tooling gem that inserts a layer between models and controllers that is tailored to REST API concerns). The specifics of graphiti aren't relevant to the issue here, other than to know that there are use cases for Pundit policies to implement and define `permitted_attributes` that aren't strictly limited to use within controllers. Ergo, the verbiage of "mass assignment" doesn't really apply.

(For more context, the use of `permitted_attributes` is for providing per-attribute `reabable`/`writable` type control at the api resource layer: https://www.graphiti.dev/guides/concepts/resources#limiting-behavior)

## primary request

So the initial proposal is to consider renaming the attribute matchers as `permit_attributes`/`forbid_attributes` which I think still read well with the chained action matcher:

```
it { is_expected.to permit_attributes(%i[name description]) }
it { is_expected.to permit_attributes(%i[name description]).for_action(:read) }
```

The argument in favor of renaming is that `permit_attributes` has use _outside_ of controllers. In particular, Pundit itself makes no assumption since policies are POROs; they set an expectation that policies implement `permitted_attributes` and so pundit-matchers (being a matcher library for pundit) is really only concerned with testing policies and need not (should not, IMO) presume the context in which those policies and their methods are used. And since the method that the matcher is asserting against is quite literally `permitted_attributes`, it seems fitting that the matcher use that verbiage (permit/forbid _attributes).

## secondary request

Of course, rspec allows aliasing matchers. We've gone that route in the interim:

```
alias_matcher :permit_serialization_of, :permit_mass_assignment_of
alias_matcher :forbid_serialization_of, :forbid_mass_assignment_of
```

However, the downside is that the failure message (and test docstrings) descriptions are not overridden consistently. The docstrings generated from "permit" seem to take the value properly from aliased matcher name: `"is expected to permit serialization of ..."` but for some reason, the docstrings from the forbid alias is _not_ accurate: `"is expected to forbid mass assignment of  mass assignment of ..."`. I suspect this is because of how pundit-matchers is currently defining the forbid negated matcher, which will _hopefully_ be resolved by the refactor that is in progress. So to summarize the second request here (regardless if the matchers are renamed): the mechanism by which pundit-matchers defines both the permit and forbid matchers should use rspec's facilities in such a way that further aliases generate the correct docstrings.

**Comment by chrisalley** [comment]
Relevant issue that contemplates revisiting `permit_mass_assignment_of`: https://github.com/punditcommunity/pundit-matchers/issues/24#issuecomment-1562566280

**Comment by chrisalley** [comment]
`permit_attributes` would make a suitable new default name for the matcher, with `permit_mass_assignment_of` acting as an alternative syntax for backward compatibility purposes.

For consistency with `permit_action`/`permit_actions` we could include `permit_attribute` (singular) syntax too.

**Comment by tagliala** [comment]
I think this is a good change and I would go for the same API of actions

Also, the matcher is internally named as `attributes`, so it would be more natural to use `permit_attributes` and `permit_attribute` rather than `permit_mass_assignment_of`

> "is expected to permit serialization of ..." but for some reason, the docstrings from the forbid alias is not accurate: "is expected to forbid mass assignment of  mass assignment of ...". I suspect this is because of how pundit-matchers is currently defining the forbid negated matcher, which will hopefully be resolved by the refactor that is in progress.

Is this still an issue on v3?

**Comment by chrisalley** [comment]
I'm thinking that we keep the `permit_mass_assignment_of` syntax around as an alternative syntax. Test suites have been using it since 2015, so removing it could be disruptive for project maintainers. `permit_mass_assignment_of` could be a helper matcher, similar to `permit_new_and_create_actions`, e.g.

`permit_mass_assignment_of(:action1)` -> `permit_attributes(%i[action1])`
`permit_mass_assignment_of([:action1, :action2])` -> `permit_attributes(%i[action1, action2])`
`permit_attribute(:action1)` -> `permit_attributes(%i[action1])`

**Comment by tagliala** [comment]
#98 should address this use case. `permit_mass_assignment_of` has been defined as an alias of `permit_attributes` (and the same for `forbid_mass_assignment_of`

The documentation refers to `permit_attributes` and `forbid_attributes` as the preferred methods
